# Generated by Django 4.0.5 on 2022-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Bazar'), (2, 'Camping'), (3, 'Rodados'), (4, 'Deportes'), (5, 'Ferretería')], verbose_name='Categoría')),
                ('cantidad_productos', models.IntegerField(verbose_name='Cantidad de productos')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Bazar'), (2, 'Camping'), (3, 'Rodados'), (4, 'Deportes'), (5, 'Ferretería')], verbose_name='Categoría')),
                ('precio', models.FloatField(verbose_name='Precio $')),
                ('stock_disponible', models.IntegerField(verbose_name='Stock disponible')),
            ],
        ),
    ]
