# Generated by Django 4.0.5 on 2022-06-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Bazar'), (2, 'Camping'), (3, 'Rodados'), (4, 'Deportes'), (5, 'Ferretería')], verbose_name='Categoria')),
                ('precio', models.FloatField(verbose_name='Precio $')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marcass',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.AlterModelOptions(
            name='marcass',
            options={'verbose_name_plural': 'Marcas'},
        ),
    ]
