# Generated by Django 4.0.5 on 2022-06-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0002_productoss_rename_marcas_marcass_delete_productos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marcass',
            new_name='Marcas',
        ),
        migrations.RenameModel(
            old_name='Productoss',
            new_name='Productos',
        ),
    ]
