# Generated by Django 4.0.5 on 2022-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0003_rename_marcass_marcas_rename_productoss_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.PositiveSmallIntegerField(choices=[(1, 'Córdoba'), (2, 'Capital Federal'), (3, 'Rosario'), (4, 'Mendoza'), (5, 'Salta')], verbose_name='Localidad')),
                ('rubro_principal', models.PositiveSmallIntegerField(choices=[(1, 'Especialista en Bazar'), (2, 'Especialista en Camping'), (3, 'Especialista en Rodados'), (4, 'Especialista en Deportes'), (5, 'Especialista en Ferretería')], verbose_name='Rubro')),
                ('horario_apertura', models.TimeField(verbose_name='Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Apertura')),
            ],
            options={
                'verbose_name_plural': 'Locales',
            },
        ),
    ]
