# Generated by Django 4.0.5 on 2022-06-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0005_localess_delete_locales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localess',
            new_name='Locales',
        ),
    ]
