# Generated by Django 4.0.5 on 2022-07-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0006_rename_localess_locales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Bazar'), (2, 'Camping'), (3, 'Rodados'), (4, 'Deportes'), (5, 'Ferretería')], verbose_name='Categoria')),
                ('precio', models.FloatField(verbose_name='Precio $')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Foto producto')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
