# Generated by Django 4.0.5 on 2022-07-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0007_producto_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
