# Generated by Django 4.0.5 on 2022-07-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0008_rename_producto_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
