# Generated by Django 4.0.5 on 2022-07-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega1App', '0010_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
